services:
  # Service Web Django
  - type: web
    name: kefystore-ecommerce
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: kefystore-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "kefystore-ecommerce.onrender.com"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
    healthCheckPath: /

  # Base de donn√©es PostgreSQL
  - type: pgsql
    name: kefystore-db
    plan: free
    databaseName: kefystore_db
    user: kefystore_user

